# Generated by Django 5.1.3 on 2024-12-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=225)),
                ('gps_location', models.CharField(max_length=225)),
                ('branch_type', models.CharField(choices=[('Headquarter', 'Headquarter'), ('Other', 'Other')], max_length=50)),
            ],
        ),
    ]
