# Generated by Django 5.1.3 on 2024-12-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchDetails',
            new_name='Branch',
        ),
    ]
