# Generated by Django 5.1.3 on 2024-12-05 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_rename_category_subcategory_parent_category'),
        ('serviceManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateTimeField()),
                ('payment_option', models.CharField(choices=[('Online', 'Online'), ('On Cilnic', 'On Cilnic')], max_length=50)),
                ('message', models.TextField()),
                ('appointment_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('select_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='category.maincategory')),
                ('select_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='category.subcategory')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='serviceManagement.ourservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
