# Generated by Django 5.1.3 on 2024-12-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0001_initial'),
        ('serviceManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmanagement',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='serviceManagement.ourservice'),
        ),
    ]
