# Generated by Django 5.1.3 on 2024-12-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0002_alter_bookingmanagement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmanagement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
