# Generated by Django 5.1.3 on 2024-12-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0004_remove_bookingmanagement_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmanagement',
            name='select_test',
        ),
    ]
